# Generated by Django 6.0.7 on 2026-07-14 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Scene Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Scene Description/Content"
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="scene_media/",
                        verbose_name="Media File (Video or Image)",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("VIDEO", "Video"), ("IMAGE", "Image")],
                        default="IMAGE",
                        max_length=10,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "decision_trigger_time",
                    models.FloatField(
                        blank=True,
                        help_text="Timestamp in seconds at which choices should appear (Videos only). If null, they appear immediately.",
                        null=True,
                        verbose_name="Decision Trigger Time",
                    ),
                ),
                (
                    "pause_on_decision",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to pause the video when choices are displayed.",
                        verbose_name="Pause on Decision",
                    ),
                ),
                (
                    "timer_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Time in seconds that the player has to make a choice. If null, there is no time limit.",
                        null=True,
                        verbose_name="Timer Duration",
                    ),
                ),
                (
                    "default_next_scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="The next scene to transition to if the timer expires without user interaction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_fallback_for",
                        to="core.scene",
                        verbose_name="Default Fallback Scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene",
                "verbose_name_plural": "Scenes",
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Choice Button Text"),
                ),
                (
                    "next_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_choices",
                        to="core.scene",
                        verbose_name="Target Destination Scene",
                    ),
                ),
                (
                    "source_scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="core.scene",
                        verbose_name="Source Scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice",
                "verbose_name_plural": "Choices",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Story Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Story Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_scene",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="starting_story",
                        to="core.scene",
                        verbose_name="Starting Scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
            },
        ),
        migrations.AddField(
            model_name="scene",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenes",
                to="core.story",
                verbose_name="Story",
            ),
        ),
    ]
