# Generated by Django 6.0.7 on 2026-07-14 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="resource_1_impact",
            field=models.IntegerField(default=0, verbose_name="Resource 1 Impact"),
        ),
        migrations.AddField(
            model_name="choice",
            name="resource_2_impact",
            field=models.IntegerField(default=0, verbose_name="Resource 2 Impact"),
        ),
        migrations.CreateModel(
            name="StoryResourceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "use_resource_system",
                    models.BooleanField(
                        default=False, verbose_name="Use Resource System"
                    ),
                ),
                (
                    "resource_1_name",
                    models.CharField(
                        default="Presupuesto",
                        max_length=50,
                        verbose_name="Resource 1 Name",
                    ),
                ),
                (
                    "resource_2_name",
                    models.CharField(
                        default="Moral", max_length=50, verbose_name="Resource 2 Name"
                    ),
                ),
                (
                    "resource_1_initial_value",
                    models.IntegerField(
                        default=100, verbose_name="Resource 1 Initial Value"
                    ),
                ),
                (
                    "resource_2_initial_value",
                    models.IntegerField(
                        default=100, verbose_name="Resource 2 Initial Value"
                    ),
                ),
                (
                    "resource_1_game_over_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_over_for_r1",
                        to="core.scene",
                        verbose_name="Resource 1 Game Over Scene",
                    ),
                ),
                (
                    "resource_2_game_over_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_over_for_r2",
                        to="core.scene",
                        verbose_name="Resource 2 Game Over Scene",
                    ),
                ),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_config",
                        to="core.story",
                        verbose_name="Story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Resource Config",
                "verbose_name_plural": "Story Resource Configs",
            },
        ),
    ]
