# Generated by Django 6.0.7 on 2026-07-14 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_choice_resource_1_impact_choice_resource_2_impact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="resource_1_impact",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="resource_2_impact",
        ),
        migrations.CreateModel(
            name="StoryResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Resource Name"),
                ),
                (
                    "initial_value",
                    models.IntegerField(default=100, verbose_name="Initial Value"),
                ),
                (
                    "trigger_limit",
                    models.IntegerField(
                        default=0, verbose_name="Trigger Threshold Limit"
                    ),
                ),
                (
                    "trigger_condition",
                    models.CharField(
                        choices=[
                            ("LTE", "Menor o igual que (<=)"),
                            ("GTE", "Mayor o igual que (>=)"),
                        ],
                        default="LTE",
                        max_length=5,
                        verbose_name="Trigger Condition Rule",
                    ),
                ),
                (
                    "game_over_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_over_for_resources",
                        to="core.scene",
                        verbose_name="Game Over Fallback Scene",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_resources",
                        to="core.story",
                        verbose_name="Story",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Resource",
                "verbose_name_plural": "Story Resources",
            },
        ),
        migrations.CreateModel(
            name="ChoiceResourceImpact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "impact_value",
                    models.IntegerField(default=0, verbose_name="Impact Value (+/-)"),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_impacts",
                        to="core.choice",
                        verbose_name="Choice",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacts",
                        to="core.storyresource",
                        verbose_name="Target Resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice Resource Impact",
                "verbose_name_plural": "Choice Resource Impacts",
            },
        ),
        migrations.DeleteModel(
            name="StoryResourceConfig",
        ),
    ]
