# Generated by Django 6.0.7 on 2026-07-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_room_participant_vote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("room", "nickname")},
        ),
        migrations.AlterField(
            model_name="participant",
            name="session_key",
            field=models.CharField(
                db_index=True,
                max_length=255,
                verbose_name="Reconnect Session Identifier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("room", "nickname"), ("room", "session_key")},
        ),
    ]
