# Generated by Django 6.0.7 on 2026-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_participant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="avatar",
            field=models.CharField(
                default="👤", max_length=10, verbose_name="Player Avatar Emoji"
            ),
        ),
    ]
