# Generated by Django 6.0.7 on 2026-07-14 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_participant_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="reaction_time_ms",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Reaction Time (ms)"
            ),
        ),
        migrations.CreateModel(
            name="VoteRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reaction Time (ms)"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "choice_made",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records_choice",
                        to="core.choice",
                        verbose_name="Choice Made",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to="core.participant",
                        verbose_name="Participant",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records",
                        to="core.room",
                        verbose_name="Room",
                    ),
                ),
                (
                    "scene_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records_from",
                        to="core.scene",
                        verbose_name="Scene From",
                    ),
                ),
                (
                    "scene_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_records_to",
                        to="core.scene",
                        verbose_name="Scene To",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote Record",
                "verbose_name_plural": "Vote Records",
            },
        ),
    ]
