# Generated by Django 6.0.7 on 2026-07-14 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_vote_reaction_time_ms_voterecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="host_key",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                verbose_name="Host Secret Reconnection Key",
            ),
        ),
    ]
