# Generated by Django 6.0.7 on 2026-07-14 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_room_host_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author/Creator",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Is Public Story"),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Host Admin",
            ),
        ),
    ]
